### ISSUE TITLE
Entity Framework Model issue for Upload records functionality

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Climsoft#36]
The model currently has a relationship which only allows one record in the `observationinitial` table per station. The code for the Upload feature is written but currently commented until this is resolved. It should be solvable by a small change to the model.

**Comment by isedwards** [comment]
I think this may be related to the same problem that we are having in #18 (where tables are missing from the EF model due to the lack of a single-column primary key id).  See #75 for any attempted solution to both.

If #75 doesn't fix the issue when writing multiple records into `observationinitial` (i.e. the foreign key between stationId and recordedFrom is still not correctly recognised as 1-to-many) then we'll have to look at the data annotations in the generated model, check our [composite key](https://msdn.microsoft.com/en-us/library/jj591583(v=vs.113).aspx#Composite-keys) and also the `stationId` foreign key.

Hopefully we won't have to make manual changes to the model - ideally we want all changes to the database to be picked up automatically.

**Comment by isedwards** [comment]
I've not tested the result of #100 on this issue - but my model designer is still showing a one to zero-or-one relationship between `station` and `observationinitial` despite there now being a composite primary key on the table. It suggests that each station id can only be represented once still.

Let me know if this is still the case. A short term fix, that's should work, would be to remove the foreign keys from the model temporarily (and just make sure the correct ids are written into `observationinitial` without the database enforcing this). Removing the foreign keys is just a case of opening the model designer, selecting the relation and choosing delete.

Does this solve our problem prior to the Friday deadline and the initial merge with upstream?

It should be possible to work out how to fix this long term since there are plenty of other relationships in the model that are one to many.

**Comment by maxwellfundi** [comment]
This has also been addressed with the latest update to the model. Upload now works well. Could be closed?

**Comment by mhabimana** [comment]
@maxwellfundi : I cloned the latest PR yesterday and I am using the "dev" branch  but the upload button is not active on all the data entry forms under this branch. I wonder if  you have updated this branch with the latest changes ( including the upload button functionalities) or not yet.

**Comment by maxwellfundi** [comment]
@mhabimana  This should now be working for you. I am closing this now.

**Comment by mhabimana** [comment]
@maxwellfundi : Thanks,noted.

**Comment by mhabimana** [comment]
@maxwellfundi :The upload button is working well but some thing to show the progress of data transfer should be added to notify users on the progress of this operation..

**Comment by maxwellfundi** [comment]
@mhabimana Yes, this could be added and we could actually use the currently existing dialog.
