### ISSUE TITLE
Issues with total

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Climsoft#76]
![image](https://user-images.githubusercontent.com/9798689/40657368-4608ba54-6350-11e8-8a4a-b035f2e860f0.png)

This message box should have the computed total. Further, we need to make sure that if there is nothing in the total box the Val <> 0

**Comment by Patowhiz** [comment]
@maxwellfundi I don't understand the last point, what do you mean by "we need to make sure that if there is nothing in the total box the Val <> 0"?  Do you mean that when there is nothing in the total box then we shouldn't do the check?

**Comment by maxwellfundi** [comment]
So what @mhabimana  and @smachua were saying was that for example, if an element needs a total, then when there is nothing (user has not put in anything) on the total box then a message would be that total is required not the message box we currently have that says total computed by computer is different from what whats entered. This is brought about by when we do `val(txttotal.GetValue)` equates to 0. 
@smachua  @mhabimana could get this clearer if its not clear yet.

**Comment by mhabimana** [comment]
@Patowhiz, @maxwellfundi : The total value displays in the total text box is just for QC purpose and it should not be saved anywhere in the database. As @maxwellfundi  says, zero (0) is a value and  it means there was no rains but it does not mean nothing. Having the total computed by the computer and displayed in the message box is very helpful because it prompts the data entry personnel to compare what   is on the data form and what the computer is suggesting to him. If the total is left blank,the cursor should block until you put in the correct value displayed/suggested in the message box.

**Comment by Patowhiz** [comment]
@mhabina thank you for the clarity.

**Comment by Patowhiz** [comment]
This has been addressed on all the data entry forms that require this functionality
