### ISSUE TITLE
Typing in to the Station and element selector

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Climsoft#79]
A desired thing on this is that regardless of which view you are in (Either from the ids, Ids and names or Names), the user should see the names of elements/station names when they type in a number(id) for the elements/stations.

@africanmathsinitiative/climsoft-developers  Do we encourage them to have the default view type as ids and names?

**Comment by mhabimana** [comment]
@maxwellfundi 
Below is an e.g of a daily form with station name and station element displayed by default. Now let say you want to change the station name and element name, In this case instead of using the drop down box,you can simply type the stationId to call the station name in the text box and type elementId to call the element name in the text box ( this  speed up the process during Data entry). By default the name should appear under station name and element name because users should see the name instead of Ids:
![image](https://user-images.githubusercontent.com/10340170/40960379-290ece86-68a8-11e8-8bd9-d9c6fd7c3b68.png)

**Comment by Patowhiz** [comment]
The easiest way to implement this will be to set the view type as Station Id and Station Name.

**Comment by Patowhiz** [comment]
@mhabimana our initial thought was that the user should only be able to search for the what he physically sees. That means, if my view type is just station id, then I can only type in station id to get the station I want, the same applies for station name. 

To be able to achieve what you are asking for we can easily set the default view type for the station and element selectors to be Ids and Names. That way the user will be able to see the ids and the names and search for either. This comes in handy with the autocomplete feature.

Or do you still insist on the user just seeing the name only and be able to search for the name through the Id?

**Comment by mhabimana** [comment]
@Patowhiz Thanks. I think your last point would be the best option since it was implemented in earlier versions and is also working well on the climsoft version4 we currently have: https://github.com/opencdms/Climsoft
By default we should have only the name and not id and since name and id are linked,you can use an id to call the name. Having both name and id will be too long.
